In [1]:
import pandas as pd
import os

In [2]:
AUDIO_DIR = "C:/Users/User/Downloads/VAE project/MERGE_Audio_Balanced" # -> DO NOT REMOVE
LYRICS_DIR = "C:/Users/User/Downloads/VAE project/MERGE_Lyrics_Balanced" # -> DO NOT REMOVE
# AUDIO_DIR = input("Enter the path to MERGE_Audio_Balanced in your device: ")
# LYRICS_DIR = input("Enter the path to MERGE_Lyrics_Balanced in your device: ")

In [3]:
audio_metadata_path = os.path.join(AUDIO_DIR, "merge_audio_balanced_metadata.csv")
lyrics_metadata_path = os.path.join(LYRICS_DIR, "merge_lyrics_balanced_metadata.csv")

In [4]:
audio_metadata = pd.read_csv(audio_metadata_path)
lyrics_metadata = pd.read_csv(lyrics_metadata_path)

In [5]:
audio_metadata.head()

,Song,Quadrant,AllMusic Id,AllMusic Extraction Date,Artist,Title,Relevance,Year,LowestYear,Duration,...,ThemeWeights,Styles,StyleWeights,AppearancesTrackIDs,AppearancesAlbumIDs,Sample,SampleURL,ActualYear,num_Genres,num_MoodsAll
0,A001,Q4,MT0000291374,New,Louis Armstrong,What a Wonderful World,NaN,NaN,NaN,139.0,...,"9,9",NaN,NaN,NaN,NaN,NaN,NaN,1968,NaN,NaN
1,A002,Q4,MT0001577585,Old,Rod Stewart,Country Comfort,1.493585,1970-??-??,NaN,282.0,...,"5,5,5,5,5,5,5,5","Adult Contemporary,Contemporary Pop/Rock","5,5","MT0001577585,MT0002372349,MT0002706336,MT00029...","MW0000073575,MW0000100670,MW0000100670,MW00001...",1.0,http://rovimusic.rovicorp.com/playback.mp3?c=s...,1970,NaN,NaN
2,A003,Q3,MT0008469560,New,Stevie Wonder,Lately,NaN,NaN,NaN,244.0,...,"7,8,9,9,9",NaN,NaN,NaN,NaN,NaN,NaN,1980,NaN,NaN
3,A004,Q3,MT0030326044,New,Johnny Cash,I'm So Lonesome I Could Cry,NaN,NaN,NaN,159.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1960,NaN,NaN
4,A005,Q1,MT0005204984,New,Prince,U Got the Look,NaN,NaN,NaN,227.0,...,"8,8,8,9,9,9",NaN,NaN,NaN,NaN,NaN,NaN,1987,NaN,NaN

In [6]:
lyrics_metadata.head()

,Song,Quadrant,AllMusic Id,AllMusic Extraction Date,Artist,Title,Relevance,Year,LowestYear,Duration,...,GenreWeights,Themes,ThemeWeights,Styles,StyleWeights,AppearancesTrackIDs,AppearancesAlbumIDs,Sample,SampleURL,ActualYear
0,L001-141,Q4,MT0013902576,New,Norah Jones,Moon Song,NaN,NaN,NaN,165.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004
1,L002-157,Q3,MT0004671597,New,John Lennon,Mother,NaN,NaN,NaN,NaN,...,"9,9,9,10","Introspection,Maverick,Revolution,Solitude,Ref...","9,9,9,9,9,9",NaN,NaN,NaN,NaN,NaN,NaN,1970
2,L004-120,Q1,MT0001671601,New,Luther Vandross,Never too Much,NaN,NaN,NaN,233.0,...,"8,8,8","Slow Dance,In Love,Romantic Evening,New Love","8,8,8,8",NaN,NaN,NaN,NaN,NaN,NaN,1981
3,L005-84,Q1,MT0004971929,New,Frank Sinatra,"New York, New York",NaN,NaN,NaN,208.0,...,"7,7,7,8,9,9","Guys Night Out,Partying,Drinking,Motivation,Di...","7,7,7,8,9,9,9,9,9",NaN,NaN,NaN,NaN,NaN,NaN,1979
4,L007-76,Q3,MT0002620427,New,Sinï¿½ad O'Connor,Nothing Compares 2 U,NaN,NaN,NaN,310.0,...,"7,7,8,8,8","Rainy Day,Regret,Heartache,Feeling Blue","7,7,7,8",NaN,NaN,NaN,NaN,NaN,NaN,1990

In [7]:
audio_metadata.columns, lyrics_metadata.columns

(Index(['Song', 'Quadrant', 'AllMusic Id', 'AllMusic Extraction Date', 'Artist',
        'Title', 'Relevance', 'Year', 'LowestYear', 'Duration', 'Moods',
        'MoodsAll', 'MoodsAllWeights', 'Genres', 'GenreWeights', 'Themes',
        'ThemeWeights', 'Styles', 'StyleWeights', 'AppearancesTrackIDs',
        'AppearancesAlbumIDs', 'Sample', 'SampleURL', 'ActualYear',
        'num_Genres', 'num_MoodsAll'],
       dtype='str'),
 Index(['Song', 'Quadrant', 'AllMusic Id', 'AllMusic Extraction Date', 'Artist',
        'Title', 'Relevance', 'Year', 'LowestYear', 'Duration', 'Moods',
        'MoodsAll', 'MoodsAllWeights', 'Genres', 'GenreWeights', 'Themes',
        'ThemeWeights', 'Styles', 'StyleWeights', 'AppearancesTrackIDs',
        'AppearancesAlbumIDs', 'Sample', 'SampleURL', 'ActualYear'],
       dtype='str'))

In [8]:
sorted_audio_metadata = audio_metadata.sort_values(by="AllMusic Id")
sorted_lyrics_metadata = lyrics_metadata.sort_values(by="AllMusic Id")

In [9]:
sorted_audio_metadata.columns, sorted_lyrics_metadata.columns

(Index(['Song', 'Quadrant', 'AllMusic Id', 'AllMusic Extraction Date', 'Artist',
        'Title', 'Relevance', 'Year', 'LowestYear', 'Duration', 'Moods',
        'MoodsAll', 'MoodsAllWeights', 'Genres', 'GenreWeights', 'Themes',
        'ThemeWeights', 'Styles', 'StyleWeights', 'AppearancesTrackIDs',
        'AppearancesAlbumIDs', 'Sample', 'SampleURL', 'ActualYear',
        'num_Genres', 'num_MoodsAll'],
       dtype='str'),
 Index(['Song', 'Quadrant', 'AllMusic Id', 'AllMusic Extraction Date', 'Artist',
        'Title', 'Relevance', 'Year', 'LowestYear', 'Duration', 'Moods',
        'MoodsAll', 'MoodsAllWeights', 'Genres', 'GenreWeights', 'Themes',
        'ThemeWeights', 'Styles', 'StyleWeights', 'AppearancesTrackIDs',
        'AppearancesAlbumIDs', 'Sample', 'SampleURL', 'ActualYear'],
       dtype='str'))

In [10]:
sorted_lyrics_metadata = sorted_lyrics_metadata.rename(columns={"Song": "Lyrics"})

In [11]:
common_columns = [col for col in  sorted_audio_metadata.columns if col in sorted_lyrics_metadata.columns]
common_columns

['Quadrant',
 'AllMusic Id',
 'AllMusic Extraction Date',
 'Artist',
 'Title',
 'Relevance',
 'Year',
 'LowestYear',
 'Duration',
 'Moods',
 'MoodsAll',
 'MoodsAllWeights',
 'Genres',
 'GenreWeights',
 'Themes',
 'ThemeWeights',
 'Styles',
 'StyleWeights',
 'AppearancesTrackIDs',
 'AppearancesAlbumIDs',
 'Sample',
 'SampleURL',
 'ActualYear']

In [12]:
merged_metadata = sorted_audio_metadata.merge(sorted_lyrics_metadata, how="outer", on="AllMusic Id")
merged_metadata.head()

,Song,Quadrant_x,AllMusic Id,AllMusic Extraction Date_x,Artist_x,Title_x,Relevance_x,Year_x,LowestYear_x,Duration_x,...,GenreWeights_y,Themes_y,ThemeWeights_y,Styles_y,StyleWeights_y,AppearancesTrackIDs_y,AppearancesAlbumIDs_y,Sample_y,SampleURL_y,ActualYear_y
0,MT0000004637,Q3,MT0000004637,Old,Charlie Poole,Bulldog Down in Sunny Tennessee,1.010757,17/05/2005,17/05/2005,160.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,MT0000008995,Q3,MT0000008995,Old,Billie Holiday,You're Too Lovely to Last,1.058075,NaN,NaN,NaN,...,"7, 9, 9","Feeling Blue, Heartache, Introspection, Late N...","7, 9, 9, 9, 9","Classic Female Blues, Standards, Swing, Torch ...","7, 7, 8, 8, 9, 9",NaN,NaN,1.0,http://rovimusic.rovicorp.com/playback.mp3?c=6...,NaN
2,MT0000010219,Q3,MT0000010219,Old,The Ambassadors,Darling I'm Sorry,1.022643,25/07/1995,25/07/1995,129.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,MT0000010844,Q4,MT0000010844,Old,Willie Nelson,Blame It on the Times,1.500493,23/08/2005,NaN,137.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,MT0000011357,Q2,MT0000011357,Old,Dismember,Reborn in Blasphemy,1.011656,07/09/1993,1992-??-??,287.0,...,"5, 5, 5",NaN,NaN,"Club/Dance, Death Metal, Heavy Metal","5, 5, 5","MT0000011357, MT0001139826, MT0001497104, MT00...","MW0000106176, MW0000106176, MW0000645476, MW00...",1.0,http://rovimusic.rovicorp.com/playback.mp3?c=0...,1993

In [13]:
merged_dataset_common_columns = [col for col in merged_metadata.columns if col[:-2] in common_columns]
merged_dataset_common_columns

['Quadrant_x',
 'AllMusic Extraction Date_x',
 'Artist_x',
 'Title_x',
 'Relevance_x',
 'Year_x',
 'LowestYear_x',
 'Duration_x',
 'Moods_x',
 'MoodsAll_x',
 'MoodsAllWeights_x',
 'Genres_x',
 'GenreWeights_x',
 'Themes_x',
 'ThemeWeights_x',
 'Styles_x',
 'StyleWeights_x',
 'AppearancesTrackIDs_x',
 'AppearancesAlbumIDs_x',
 'Sample_x',
 'SampleURL_x',
 'ActualYear_x',
 'Quadrant_y',
 'AllMusic Extraction Date_y',
 'Artist_y',
 'Title_y',
 'Relevance_y',
 'Year_y',
 'LowestYear_y',
 'Duration_y',
 'Moods_y',
 'MoodsAll_y',
 'MoodsAllWeights_y',
 'Genres_y',
 'GenreWeights_y',
 'Themes_y',
 'ThemeWeights_y',
 'Styles_y',
 'StyleWeights_y',
 'AppearancesTrackIDs_y',
 'AppearancesAlbumIDs_y',
 'Sample_y',
 'SampleURL_y',
 'ActualYear_y']

In [14]:
merged_metadata[merged_dataset_common_columns].isnull().sum()

Quadrant_x                     269
AllMusic Extraction Date_x     269
Artist_x                       272
Title_x                        269
Relevance_x                    454
Year_x                         582
LowestYear_x                  1207
Duration_x                     430
Moods_x                        454
MoodsAll_x                     306
MoodsAllWeights_x              309
Genres_x                       301
GenreWeights_x                 301
Themes_x                       795
ThemeWeights_x                 795
Styles_x                       474
StyleWeights_x                 474
AppearancesTrackIDs_x          568
AppearancesAlbumIDs_x          568
Sample_x                       454
SampleURL_x                    468
ActualYear_x                   420
Quadrant_y                    1101
AllMusic Extraction Date_y    1101
Artist_y                      1101
Title_y                       1101
Relevance_y                   1330
Year_y                        1444
LowestYear_y                  1973
Duration_y                    1261
Moods_y                       1321
MoodsAll_y                    1128
MoodsAllWeights_y             1138
Genres_y                      1129
GenreWeights_y                1129
Themes_y                      1511
ThemeWeights_y                1511
Styles_y                      1346
StyleWeights_y                1346
AppearancesTrackIDs_y         1432
AppearancesAlbumIDs_y         1432
Sample_y                      1330
SampleURL_y                   1355
ActualYear_y                  1239
dtype: int64

In [15]:
merged_metadata[["Song", "Lyrics"]].isnull().sum()

Song       269
Lyrics    1101
dtype: int64

In [16]:
relevant_dataset = merged_metadata[["Song", "Lyrics", "Quadrant_x", "Quadrant_y", "Genres_x", "Genres_y"]]

In [17]:
audio_lyrics_not_null = relevant_dataset.dropna(subset=["Song", "Lyrics", "Genres_x", "Genres_y"])

In [18]:
audio_lyrics_not_null.reset_index(inplace=True, drop=True)

In [19]:
audio_lyrics_not_null.info()

<class 'pandas.DataFrame'>
RangeIndex: 2118 entries, 0 to 2117
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Song        2118 non-null   str
 1   Lyrics      2118 non-null   str
 2   Quadrant_x  2118 non-null   str
 3   Quadrant_y  2118 non-null   str
 4   Genres_x    2118 non-null   str
 5   Genres_y    2118 non-null   str
dtypes: str(6)
memory usage: 99.4 KB

In [20]:
metadata_df = audio_lyrics_not_null.drop(columns=["Quadrant_y", "Genres_y"]).rename(columns={"Song": "audio_file_stem", "Lyrics": "lyric_file_stem", "Quadrant_x": "quadrant", "Genres_x": "genres"})
metadata_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2118 entries, 0 to 2117
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   audio_file_stem  2118 non-null   str
 1   lyric_file_stem  2118 non-null   str
 2   quadrant         2118 non-null   str
 3   genres           2118 non-null   str
dtypes: str(4)
memory usage: 66.3 KB

In [21]:
metadata_df

,audio_file_stem,lyric_file_stem,quadrant,genres
0,MT0000008995,MT0000008995,Q3,"Blues,Jazz,Vocal"
1,MT0000011357,MT0000011357,Q2,"Electronic,International,Pop/Rock"
2,MT0000026571,MT0000026571,Q4,Vocal
3,MT0000027422,MT0000027422,Q3,Pop/Rock
4,MT0000030834,MT0000030834,Q4,Jazz
...,...,...,...,...
2113,A088-136,L138-136,Q4,"Traditional Pop,Standards,Vocal,Vocal Jazz,Jazz"
2114,A064-116,L114-116,Q1,"R&B,Adult Contemporary,Urban,Contemporary Pop/..."
2115,A066-140,L116-140,Q4,"Holiday,Holidays,Christmas,Celtic New Age,Ethn..."
2116,A137-153,L027-153,Q4,"Jazz Blues,Vocal Jazz,Jazz,Alternative/Indie R..."
2117,A151-172,L041-172,Q2,"Hard Rock,Heavy Metal,Album Rock,British Metal..."

###

In [22]:
metadata_df.to_csv("../../../data/metadata/metadata_en.csv", index=False)