In [15]:
import pandas as pd
from pathlib import Path

In [16]:
from config import config

In [17]:
root = Path("../..")

In [18]:
en_meta_path = root / config.METADATA_DIR / "metadata_en.csv"
bn_meta_path = root / config.METADATA_DIR / "bn/metadata_bn.csv"
en_meta_path.exists(), bn_meta_path.exists() # has to be True

(True, True)

In [19]:
en_meta_df = pd.read_csv(en_meta_path)
bn_meta_df = pd.read_csv(bn_meta_path)

In [20]:
en_meta_df.head()

,audio_file_stem,lyric_file_stem,quadrant,genres,label
0,A001,L051,Q4,"Jazz,Vocal Jazz,Traditional Pop,Early Pop/Rock...",2
1,A002,L052,Q4,Pop/Rock,2
2,A003,L053,Q3,"Soul,Pop-Soul,Smooth Soul,R&B",3
3,A004,L054,Q3,"Outlaw Country,Country",3
4,A005,L055,Q1,"Dance-Rock,R&B,Contemporary Pop/Rock,Contempor...",0

In [21]:
bn_meta_df.head()

,id,sentence,genre
0,8dLOs8LK4OQ_seg_00001,না না না না না স্বপ্নের বালুকায়,Pop
1,8dLOs8LK4OQ_seg_00002,কেউ কি পালুকায় যদি না আসে ভেজা দিন ইচ্ছে হিমা...,Pop
2,8dLOs8LK4OQ_seg_00003,থাকে অমলিন কিছু স্বপ্ন কিছু ইচ্ছে এই আমায় টেন...,Pop
3,8dLOs8LK4OQ_seg_00004,কেউ না জানুক আমি তো জানি আমি তোমার কেউ না জানু...,Pop
4,8dLOs8LK4OQ_seg_00005,কেউ না জানো আমি তো জানি আমি তোমার,Pop

In [22]:
en_meta_df["language"] = "en"
en_meta_df["label"] = 0
bn_meta_df["language"] = "bn"
bn_meta_df["label"] = 1
bn_meta_df.rename(columns={"id": "audio_file_stem"}, inplace=True)
en_meta_df.rename(columns={"genres": "genre"}, inplace=True)

In [23]:
en_meta_df

,audio_file_stem,lyric_file_stem,quadrant,genre,label,language
0,A001,L051,Q4,"Jazz,Vocal Jazz,Traditional Pop,Early Pop/Rock...",0,en
1,A002,L052,Q4,Pop/Rock,0,en
2,A003,L053,Q3,"Soul,Pop-Soul,Smooth Soul,R&B",0,en
3,A004,L054,Q3,"Outlaw Country,Country",0,en
4,A005,L055,Q1,"Dance-Rock,R&B,Contemporary Pop/Rock,Contempor...",0,en
...,...,...,...,...,...,...
1983,MT0035974819,MT0035974819,Q3,"Country,Pop/Rock",0,en
1984,MT0036111757,MT0036111757,Q2,Pop/Rock,0,en
1985,MT0036368550,MT0036368550,Q1,Pop/Rock,0,en
1986,MT0039250520,MT0039250520,Q2,Rap,0,en
1987,MT0041030749,MT0041030749,Q4,Holiday,0,en

In [24]:
bn_meta_df

,audio_file_stem,sentence,genre,language,label
0,8dLOs8LK4OQ_seg_00001,না না না না না স্বপ্নের বালুকায়,Pop,bn,1
1,8dLOs8LK4OQ_seg_00002,কেউ কি পালুকায় যদি না আসে ভেজা দিন ইচ্ছে হিমা...,Pop,bn,1
2,8dLOs8LK4OQ_seg_00003,থাকে অমলিন কিছু স্বপ্ন কিছু ইচ্ছে এই আমায় টেন...,Pop,bn,1
3,8dLOs8LK4OQ_seg_00004,কেউ না জানুক আমি তো জানি আমি তোমার কেউ না জানু...,Pop,bn,1
4,8dLOs8LK4OQ_seg_00005,কেউ না জানো আমি তো জানি আমি তোমার,Pop,bn,1
...,...,...,...,...,...
336,Z4HpPn56LaQ_seg_00005,না অন্ধকারে হাতরে বেড়ায় মনের ভেতর চলছে লড়াই...,Indie/Folk-Pop,bn,1
337,Z4HpPn56LaQ_seg_00006,দাঁড়ায় অদ্ভুত সব মানুষগুলো কিসের খোঁজে ছুটছে...,Indie/Folk-Pop,bn,1
338,Z4HpPn56LaQ_seg_00007,মাঠ পেরিয়ে ছোট্ট বাজার হাট পেরিয়ে,Indie/Folk-Pop,bn,1
339,Z4HpPn56LaQ_seg_00008,পথ ভুলে গেছি অচেনা এই ইট পাথরের শহরে মিশে আছে ...,Indie/Folk-Pop,bn,1
340,Z4HpPn56LaQ_seg_00009,যদি সত্যি মেলে মুক্তি আমি ফিরবো না কখনো কোন দে...,Indie/Folk-Pop,bn,1

In [25]:
bn_meta_df[bn_meta_df["audio_file_stem"] == "-Bfa-aVa7MU_seg_00002"]

,audio_file_stem,sentence,genre,language,label
27,-Bfa-aVa7MU_seg_00002,দূরু তোমার উতাস চুলের ভাজে মৃদু যোছনা মাখা গন্ধ,Rock,bn,1

In [26]:
combined_meta_df = pd.concat([en_meta_df[["audio_file_stem", "language", "label", "genre"]], bn_meta_df[["audio_file_stem", "language", "label", "genre"]]], axis=0)
combined_meta_df.reset_index(drop=True, inplace=True)

In [27]:
combined_meta_df

,audio_file_stem,language,label,genre
0,A001,en,0,"Jazz,Vocal Jazz,Traditional Pop,Early Pop/Rock..."
1,A002,en,0,Pop/Rock
2,A003,en,0,"Soul,Pop-Soul,Smooth Soul,R&B"
3,A004,en,0,"Outlaw Country,Country"
4,A005,en,0,"Dance-Rock,R&B,Contemporary Pop/Rock,Contempor..."
...,...,...,...,...
2324,Z4HpPn56LaQ_seg_00005,bn,1,Indie/Folk-Pop
2325,Z4HpPn56LaQ_seg_00006,bn,1,Indie/Folk-Pop
2326,Z4HpPn56LaQ_seg_00007,bn,1,Indie/Folk-Pop
2327,Z4HpPn56LaQ_seg_00008,bn,1,Indie/Folk-Pop
2328,Z4HpPn56LaQ_seg_00009,bn,1,Indie/Folk-Pop

In [28]:
DEST_PATH = root / config.METADATA_DIR / "metadata_en_bn.csv"
combined_meta_df.to_csv(DEST_PATH, index=False)