In [1]:
import pandas as pd
from pathlib import Path

In [2]:
from config import config

In [3]:
root = Path("../..")

In [4]:
en_meta_path = root / config.METADATA_DIR / "metadata_en.csv"
bn_meta_path = root / config.METADATA_DIR / "bn/metadata_bn.csv"
en_meta_path.exists(), bn_meta_path.exists() # has to be True

(True, True)

In [5]:
en_meta_df = pd.read_csv(en_meta_path)
bn_meta_df = pd.read_csv(bn_meta_path)

In [6]:
en_meta_df.head()

,audio_file_stem,lyric_file_stem,quadrant,genres,label
0,A001,L051,Q4,"Jazz,Vocal Jazz,Traditional Pop,Early Pop/Rock...",2
1,A002,L052,Q4,Pop/Rock,2
2,A003,L053,Q3,"Soul,Pop-Soul,Smooth Soul,R&B",3
3,A004,L054,Q3,"Outlaw Country,Country",3
4,A005,L055,Q1,"Dance-Rock,R&B,Contemporary Pop/Rock,Contempor...",0

In [7]:
bn_meta_df.head()

,id,sentence,predicted_genre,confidence,predicted_label_idx
0,8dLOs8LK4OQ_seg_00001,না না না না না স্বপ্নের বালুকায়,আধুনিক,0.723387,0
1,8dLOs8LK4OQ_seg_00002,কেউ কি পালুকায় যদি না আসে ভেজা দিন ইচ্ছে হিমা...,আধুনিক,0.842494,0
2,8dLOs8LK4OQ_seg_00003,থাকে অমলিন কিছু স্বপ্ন কিছু ইচ্ছে এই আমায় টেন...,আধুনিক,0.823070,0
3,8dLOs8LK4OQ_seg_00004,কেউ না জানুক আমি তো জানি আমি তোমার কেউ না জানু...,আধুনিক,0.875147,0
4,8dLOs8LK4OQ_seg_00005,কেউ না জানো আমি তো জানি আমি তোমার,আধুনিক,0.673784,0

In [8]:
en_meta_df["language"] = "en"
en_meta_df["label"] = 0
bn_meta_df["language"] = "bn"
bn_meta_df["label"] = 1
bn_meta_df.rename(columns={"id": "audio_file_stem"}, inplace=True)

In [9]:
bn_meta_df

,audio_file_stem,sentence,predicted_genre,confidence,predicted_label_idx,language,label
0,8dLOs8LK4OQ_seg_00001,না না না না না স্বপ্নের বালুকায়,আধুনিক,0.723387,0,bn,1
1,8dLOs8LK4OQ_seg_00002,কেউ কি পালুকায় যদি না আসে ভেজা দিন ইচ্ছে হিমা...,আধুনিক,0.842494,0,bn,1
2,8dLOs8LK4OQ_seg_00003,থাকে অমলিন কিছু স্বপ্ন কিছু ইচ্ছে এই আমায় টেন...,আধুনিক,0.823070,0,bn,1
3,8dLOs8LK4OQ_seg_00004,কেউ না জানুক আমি তো জানি আমি তোমার কেউ না জানু...,আধুনিক,0.875147,0,bn,1
4,8dLOs8LK4OQ_seg_00005,কেউ না জানো আমি তো জানি আমি তোমার,আধুনিক,0.673784,0,bn,1
...,...,...,...,...,...,...,...
336,Z4HpPn56LaQ_seg_00005,না অন্ধকারে হাতরে বেড়ায় মনের ভেতর চলছে লড়াই...,আধুনিক,0.822696,0,bn,1
337,Z4HpPn56LaQ_seg_00006,দাঁড়ায় অদ্ভুত সব মানুষগুলো কিসের খোঁজে ছুটছে...,ব্যান্ড,0.768665,11,bn,1
338,Z4HpPn56LaQ_seg_00007,মাঠ পেরিয়ে ছোট্ট বাজার হাট পেরিয়ে,আধুনিক,0.591311,0,bn,1
339,Z4HpPn56LaQ_seg_00008,পথ ভুলে গেছি অচেনা এই ইট পাথরের শহরে মিশে আছে ...,ব্যান্ড,0.843812,11,bn,1
340,Z4HpPn56LaQ_seg_00009,যদি সত্যি মেলে মুক্তি আমি ফিরবো না কখনো কোন দে...,ব্যান্ড,0.555548,11,bn,1

In [10]:
combined_meta_df = pd.concat([en_meta_df[["audio_file_stem", "language", "label"]], bn_meta_df[["audio_file_stem", "language", "label"]]], axis=0)
combined_meta_df.reset_index(drop=True, inplace=True)

In [11]:
combined_meta_df

            audio_file_stem language  label
0                      A001       en      0
1                      A002       en      0
2                      A003       en      0
3                      A004       en      0
4                      A005       en      0
...                     ...      ...    ...
2324  Z4HpPn56LaQ_seg_00005       bn      1
2325  Z4HpPn56LaQ_seg_00006       bn      1
2326  Z4HpPn56LaQ_seg_00007       bn      1
2327  Z4HpPn56LaQ_seg_00008       bn      1
2328  Z4HpPn56LaQ_seg_00009       bn      1

[2329 rows x 3 columns]

In [12]:
DEST_PATH = root / config.METADATA_DIR / "metadata_en_bn.csv"
combined_meta_df.to_csv(DEST_PATH, index=False)